Organization crud operations
TehanovAnton/Personal-auto-assistant pull request #16
Opened 2021-12-28 16:09 UTC by TehanovAnton

2021-12-31 12:44 UTC, TehanovAnton commented
I add associations and scaffold for Organization model. Implement CRUD operations on Organization in controller

2021-12-31 12:47 UTC, dmokreckiy commented on app/controllers/cities_controller.rb
> +    # Use callbacks to share common setup or constraints between actions.
Removed obsolete comments

2022-01-02 23:03 UTC, dmokreckiy commented on app/controllers/cities_controller.rb
> +    @cities = City.all
Sidenote for further development - needs pagination

2022-01-02 23:05 UTC, dmokreckiy commented on app/controllers/organizations_controller.rb
> +    @organization.destroy
Destory can fail and return false you know - https://devdocs.io/rails~6.1/activerecord/persistence#method-i-destroy

2022-01-02 23:18 UTC, dmokreckiy commented on app/models/organization.rb
> +  validates :adress, :email, :name, :phone_number, presence: true
You should be able to combine these two into one
`validates :adress, :email, :name, :phone_number, presence: true, uniqueness: true`

2022-01-02 23:21 UTC, dmokreckiy commented on db/migrate/20211217150125_add_omniauth_to_users.rb
> +# frozen_string_literal: true
Migrations almost always one time runners - no need to use `# frozen_string_literal: true`

2022-01-02 23:22 UTC, dmokreckiy commented on app/services/organization_service.rb
> +class OrganizationService
OK, this is wrong on so many levels...

2022-01-02 23:24 UTC, dmokreckiy commented on app/services/organization_service.rb
> +  def save_organization_and_cities_organization(organization: Organization.new,
Almost any service should have `def initialize` where you prepare all instance variables you pass on to a service. If not - this is a utility library (some calculations, etc).

2022-01-02 23:27 UTC, dmokreckiy commented on app/services/organization_service.rb
> +      CitiesOrganization.create(city_id: city_id, organization_id: organization.id)
You should not have to create an intermediate records - Rails will take care of that. Take a closer look at `physician.patients = patients` https://guides.rubyonrails.org/association_basics.html#the-has-many-through-association

2022-01-02 23:29 UTC, dmokreckiy commented on app/services/organization_service.rb
> +end
You don't even need this service. Rails will do all of these automatically with properly setuped associations. Also check out how are Forms created in Rails https://guides.rubyonrails.org/form_helpers.html

2022-01-02 23:30 UTC, dmokreckiy requested changes
Please rewrite OrganizationService with built-in Rails methods.

2022-01-02 23:35 UTC, dmokreckiy commented
@TehanovAnton No PR description

2022-01-03 21:07 UTC, dmokreckiy commented on .rubocop.yml
> +    - config/**/*
:+1:

2022-01-04 09:39 UTC, yury-yaroshyk-itechart approved these changes

2022-01-04 10:01 UTC, merged