Consumable
TehanovAnton/Personal-auto-assistant pull request #19
Opened 2021-12-29 16:26 UTC by TehanovAnton

2021-12-31 12:37 UTC, TehanovAnton commented
#9 Add business models
I create  Car and CarConsumable models, add associations. Car can have many consumables

2022-01-02 23:34 UTC, dmokreckiy commented
@TehanovAnton No PR description

2022-01-02 23:38 UTC, dmokreckiy commented on app/models/car_consumable_value.rb
> +class CarConsumableValue < ApplicationRecord
Is it a join table? If yes - naming should be different

2022-01-02 23:41 UTC, dmokreckiy commented on db/migrate/20211229160418_create_car_consumable_values.rb
> +      t.integer :value, null: false
OK, got it.

2022-01-02 23:42 UTC, dmokreckiy commented on app/models/car_consumable_value.rb
> +  belongs_to :consumable, dependent: :destroy
validates presence of value? numerical?

2022-01-02 23:43 UTC, dmokreckiy requested changes
Add `values` validations and good to go.

2022-01-04 12:40 UTC, yury-yaroshyk-itechart approved these changes

2022-01-04 13:44 UTC, merged