Part
TehanovAnton/Personal-auto-assistant pull request #20
Opened 2021-12-31 10:14 UTC by TehanovAnton

2021-12-31 12:35 UTC, TehanovAnton commented
#9 Add business models
I create Par and CarPart model. Car can have many parts

2022-01-02 23:44 UTC, dmokreckiy commented
@TehanovAnton Now I've noticed that you add you description as a comment. Please use description section of PR itself. Ask me or Yuri how to do that.

2022-01-03 00:14 UTC, dmokreckiy requested changes
Please recheck `cars_parts` table name

2022-01-03 00:14 UTC, dmokreckiy commented on app/controllers/omniauth_callbacks_controller.rb
>  end
End line missing

2022-01-03 00:14 UTC, dmokreckiy commented on db/migrate/20211229173008_create_car_parts.rb
> +    create_table :car_parts, id: false do |t|
`cars_parts` no?

2022-01-04 13:56 UTC, yury-yaroshyk-itechart approved these changes

2022-01-04 13:57 UTC, merged