Document
TehanovAnton/Personal-auto-assistant pull request #21
Opened 2021-12-31 11:38 UTC by TehanovAnton

2021-12-31 12:34 UTC, TehanovAnton commented
#9 Add business models.
I create Document and CarOwnerDocument models, add association. User can have many documents

2022-01-03 00:16 UTC, dmokreckiy commented
@TehanovAnton same as previous PR - description, reviewers, assignee.

2022-01-03 00:37 UTC, dmokreckiy commented on db/migrate/20211231104737_create_documents.rb
> +
`term_of_validity`? `срок действия документа` is always the same on each type of the document

2022-01-03 00:38 UTC, dmokreckiy commented on db/migrate/20211231105140_create_car_owner_documents.rb
> +    create_table :car_owner_documents, id: false do |t|
Join table? Naming?

2022-01-03 00:49 UTC, dmokreckiy requested changes
Please check my comments

2022-01-05 09:25 UTC, yury-yaroshyk-itechart approved these changes

2022-01-05 09:35 UTC, merged