Active storage for car
TehanovAnton/Personal-auto-assistant pull request #34
Opened 2022-05-20 15:11 UTC by TehanovAnton

2022-05-26 14:41 UTC, blackp0is0n requested changes

2022-05-26 14:41 UTC, blackp0is0n commented on app/services/pexels_service.rb
> +           .photos
?

2022-05-26 14:41 UTC, blackp0is0n commented on app/views/cars/_form.html.erb
> +    <%= image_tag photo, size: '100x100' %>
Image tag size should be limited by `CSS`

2022-05-26 14:41 UTC, blackp0is0n commented on lib/tasks/pexel.rake
> +  desc 'TODO'
Pls make description and name task according it's functionality. Currently I cannot understand what is this doing without checking it's code. Pls deal with it.

2022-05-26 14:41 UTC, blackp0is0n commented on lib/tasks/pexel.rake
> +  task download: :environment do |t|
Same

2022-05-26 14:41 UTC, blackp0is0n commented on lib/tasks/pexel.rake
> +  task :random_attach, [:count] => :environment do |t, args|
Same

2022-05-27 13:28 UTC, blackp0is0n requested changes

2022-05-27 13:28 UTC, blackp0is0n commented on app/views/cars/show.html.erb
> +<style>
Please do not use `<style>` tag, use css instead

2022-05-27 13:28 UTC, blackp0is0n commented on app/views/cars/_form.html.erb
> +    <%= image_tag photo, size: '100x100' %>
So if you moved size to css, I suppose we should drop `size` there

2022-05-27 13:28 UTC, blackp0is0n commented on app/views/cars/_form.html.erb
> +    <%= image_tag @car_form.photo.variant(resize_to_limit: [100, 100]), size: '100x100' %>
The same about size

2022-05-27 13:28 UTC, blackp0is0n commented on coverage/.last_run.json
> +  "result": {
Please add `coverage` folder to gitignore, I don't think it should be in repo

2022-05-27 13:46 UTC, TehanovAnton commented on app/views/cars/show.html.erb
> +<style>
это на долго

2022-05-30 10:44 UTC, blackp0is0n approved these changes

2022-05-30 12:01 UTC, merged